### PR TITLE
Update readme and complete doc

### PR DESCRIPTION
**Pull request by qbarthelemy**
No code modification.

### CODE REVIEW

**Review by agramfort — APPROVED** [review]

**Review by agramfort — APPROVED** [review]

**Review by sylvchev — APPROVED** [review]

**Comment by qbarthelemy** [comment]
The current description field of github is:
`Python package for covariance matrices manipulation and Biosignal classification with application in Brain Computer interface`
I suggest an update:
`Python machine learning package for biosignals processing and covariance matrices classification with Riemannian geometry`
What dou you think? @sylvchev @agramfort @plcrodrigues 
If you are ok, @agramfort, can you do the update (because I can't edit this field)?

**Comment by plcrodrigues** [comment]
Can't we say just symmetric positive definite matrices instead of covariance matrices ?

**Comment by plcrodrigues** [comment]
'Python machine learning package based on sklearn API for biosignals processing and statistical analysis of symmetric positive definite matrices using Riemannian geometry'

**Comment by agramfort** [comment]
>
> 'Python machine learning package based on sklearn API for biosignals
> processing and statistical analysis of symmetric positive definite matrices
> using Riemannian geometry'Message ID:
> ***@***.***>
>
+1

**Comment by sylvchev** [comment]
Nice! We could update the description.

**Comment by qbarthelemy** [comment]
This description is a bit long, but ok for me!

> symmetric positive definite matrices instead of covariance matrices
I agree to replace _covariance matrices_ by _positive definite matrices_ as much as possible in the doc.

**Comment by qbarthelemy** [comment]
> Python machine learning package based on sklearn API for multivariate signal processing and statistical analysis of symmetric positive definite matrices via Riemannian geometry

Since we all agree, can you update the description @agramfort?

**Comment by agramfort** [comment]
done !

**Comment by qbarthelemy** [comment]
Thanks @agramfort ! 

Do we update keywords? for eg, we could add `statistics` and `riemannian-geometry`.

**Comment by agramfort** [comment]
@qbarthelemy I gave you admin rights so you can do the updates

**Pull request merged**
