### PR TITLE
Add sample_weight parameter in TLCenter, TLStretch and TLRotate

### PR DESCRIPTION
**Pull request by apmellot**
@sylvchev @agramfort 
Following the discussion we had. I added a sample_weight parameter in .fit and .fit_transform in the 3 transfer learning classes. I tested it, and it runs properly.

### CODE REVIEW

**Review by antoinecollas — APPROVED** [review]
Looks good to me !

**Review by agramfort — COMMENTED** [review]
looks good but it needs tests

**Comment by qbarthelemy** [comment]
Ah! tests with weights failed

https://github.com/pyRiemann/pyRiemann/actions/runs/7127343018/job/19407055709?pr=273#step:7:108

**Comment by plcrodrigues** [comment]
Hi there, thanks @apmellot for your help! I'm accepting this PR and would like to point out that `sklearn` now has its [metadata routing](https://scikit-learn.org/stable/metadata_routing.html) which could be of interest to us in the near future.

**Review by plcrodrigues — APPROVED** [review]

**Pull request merged**
