### PR TITLE
Update pyRiemann from Python 3.8 - 3.10 to 3.9 - 3.11

### PR DESCRIPTION
**Pull request by qbarthelemy**

### CODE REVIEW

**Comment by agramfort** [comment]
need help?

**Comment by gcattan** [comment]
Probably ubuntu-latest in your the yaml file is still on python 3.8. 
But looks like the error is something about your joblib.
We can quickly check if this is the case by adding it to your requirement file.

**Comment by qbarthelemy** [comment]
I have updated yaml, but doc build is still KO. 
So, yes, I need help. @agramfort @gcattan 

`joblib` raises an error, because `pyriemann` is not actually installed.

**Comment by gcattan** [comment]
Hm. Actually it remembers me something. Can you try to update the sphinx action to `josh146/sphinx-action@master`

**Comment by qbarthelemy** [comment]
Wow, build is now OK!
@gcattan thank you for your help!

**Pull request merged**
