### PR TITLE
Add ajd_method parameter to CSP

### PR DESCRIPTION
**Pull request by qbarthelemy**
This PR:
- adds a parameter `ajd_method` to `CSP`, solving partially #49;
- improves `ajd` methods, replacing while loop by for-else loop;
- completes tests.

### CODE REVIEW

**Review by agramfort — APPROVED** [review]

**Comment by qbarthelemy** [comment]
The documentation has not been updated for 5 merged pull-requests.

https://pyriemann.readthedocs.io/en/latest/whatsnew.html

Any idea? @gcattan @agramfort

**Comment by gcattan** [comment]
Maybe the webhook integration needs to be updated.

**Comment by qbarthelemy** [comment]
Documentation build seems ok:
https://github.com/pyRiemann/pyRiemann/actions/runs/9898013602/job/27343835440
Is it what you are talkig about?

**Comment by gcattan** [comment]
I think the problem is rather on read the docs itself.

If you connect to https://readthedocs.org/ , you should be able to see the last build



image

**Comment by qbarthelemy** [comment]
@agramfort , can you have a look to RTD ?
or can you give rights to @gcattan ?

**Comment by agramfort** [comment]
indeed build is failing. I added gcattan <https://github.com/gcattan> to
the maintainers on readthedocs.org

**Comment by gcattan** [comment]
Thx! Build is failing as it takes too long, after adding this example to the doc: https://github.com/pyRiemann/pyRiemann/pull/306

We can disable it from running at the moment, time to think about a better solution.

**Pull request merged**
