### PR TITLE
Removed reference point check from TS.fit_transform

### PR DESCRIPTION
**Pull request by kjersbry**
This PR solves #114

### CODE REVIEW

**Comment by agramfort** [comment]
@kjersbry thanks

can you also update or add a unit test?

**Comment by sylvchev** [comment]
closes #114

**Comment by sylvchev** [comment]
Hi @kjersbry 
Could I assist you for writing the unit test? If you do not have time to do it, I could open a new PR and rebase on your work to finish the integration.

**Comment by kjersbry** [comment]
Hi! Terribly sorry for leaving this open so long. I wanted to do it but haven't had the time, so I think it is better if you do it.

**Comment by qbarthelemy** [comment]
Solved with #136.

**Pull request closed without merging**
