### PR TITLE
[FIX] Change sum by mean when computing dispersion

### PR DESCRIPTION
**Pull request by apmellot**
Related to https://github.com/pyRiemann/pyRiemann/issues/257.

### CODE REVIEW

**Review by plcrodrigues — APPROVED** [review]
I'm happy with what has been proposed by @apmellot, but I don't understand why so many tests are failing now...

@qbarthelemy ?

**Comment by qbarthelemy** [comment]
For tests, many errors should be corrected with #254. Can you review it, @plcrodrigues ?

**Review by qbarthelemy — APPROVED** [review]
If Pedro is OK, it's good for me.

**Comment by plcrodrigues** [comment]
Thanks @apmellot !

**Pull request merged**
